### ISSUE TITLE
system.war file creation location

### ISSUE THREAD

**Issue by uberskigeek** [OpenLiberty/guide-microprofile-reactive-messaging#94]
I am running on a Mac. The system.war file was generated under the start/target directory and the docker file for the system container is expecting it in start/system/target directory.

**Comment by MaiHameed** [comment]
Hi @uberskigeek, could you provide the logs of running the `mvn package` command in the start directory please? I ran through the guide up to the `.war` creation and can't seem to reproduce the problem. See:

```
[INFO] --- maven-war-plugin:3.2.3:war (default-war) @ system ---
[INFO] Packaging webapp
[INFO] Assembling webapp [system] in [/Users/maihameed@ibm.com/guide-microprofile-reactive-messaging/start/system/target/system]
[INFO] Processing war project
[INFO] Copying webapp resources [/Users/maihameed@ibm.com/guide-microprofile-reactive-messaging/start/system/src/main/webapp]
[INFO] Webapp assembled in [114 msecs]
[INFO] Building war: /Users/maihameed@ibm.com/guide-microprofile-reactive-messaging/start/system/target/system.war
```

**Comment by gkwan-ibm** [comment]
close this issue:
- cannot be reproduced
- didn't get additional information for 5 months


@uberskigeek if you still encounter the problem, you may reopen this issue and provide us the following information:
- what did you do so that the system.war was generated under the start/target?

Based on the guide, create all required files and then do following commands:
```
cd start
mvn -pl models install
mvn package
```
The system.war should be generated at start/system/target/system.war

**Comment by d3minem** [comment]
This command does not work: 

`docker build -t system:1.0-SNAPSHOT system/.`

**Error:**
                                                                                                                                                       
```
 => CACHED [2/4] COPY --chown=1001:0 src/main/liberty/config /config/                                                                                                                          0.0s
 => ERROR [3/4] COPY --chown=1001:0 target/system.war /config/apps                                                                                                                             0.0s
------
 > [3/4] COPY --chown=1001:0 target/system.war /config/apps:
```
That's the error or situation @uberskigeek and myself facing. Docker file is inside the `finish` directory and **.war** file is generated inside the `start`directory. The above command will not work in one go.
